# Generated by Django 2.2.19 on 2022-08-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220829_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='unit',
        ),
    ]
