# Generated by Django 2.2.19 on 2022-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredientamount_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredient_amount', to='recipes.Ingredient'),
        ),
    ]
