# Generated by Django 2.2.19 on 2022-08-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220830_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.Ingredient'),
            preserve_default=False,
        ),
    ]
