# Generated by Django 4.1.1 on 2022-09-21 18:14

from django.conf import settings
from django.db import migrations, models
import recipes.functions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_alter_cart_recipe_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(recipes.functions.get_or_create_deleted_user), related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
    ]
