# Generated by Django 4.1.1 on 2022-09-27 21:26

import os
from csv import DictReader

from django.db import migrations
from recipes.models import Ingredient


def copy_ingredients(apps, schema_editor):
    path = os.path.join(
        os.path.dirname(__file__), 'ingredients.csv'
    )
#        '..', '..', '..',
#        'data', 'ingredients.csv'
#    )
    temp_pk = 0
    for row in DictReader(open(path)):
        ingredient = Ingredient(
            pk=temp_pk+1,
            name=row['name'],
            measurement_unit=row['measurement_unit'],
        )
        temp_pk += 1
        ingredient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_ingredients),
    ]
